#!/bin/bash

############
# Keybinding
############

# Super+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super Return spawn footclient

# Super+C to close the focused view
riverctl map normal Super C close

# Super+Shift+Q to exit river
riverctl map normal Super+Shift Q exit

# Reload
riverctl map normal Super+Shift R spawn "$HOME/.config/river/init"

# Rofi menu
riverctl map normal Super Q spawn 'rofi -show power-menu -modi power-menu:rofi-power-menu'

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super H focus-view left
riverctl map normal Super L focus-view right

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift L swap right

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom
riverctl map normal Super X zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Control H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift+Control H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift+Control L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << (i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super "$i" set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift "$i" set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control "$i" toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags
riverctl map normal Super A set-focused-tags $all_tags
riverctl map normal Super+Shift A set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super+Shift Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Shift Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Shift Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Shift Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'swayosd-client --output-volume raise || pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'swayosd-client --output-volume lower || pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map $mode None XF86AudioMute         spawn 'swayosd-client --output-volume mute-toggle || pactl set-sink-mute @DEFAULT_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done


##############
# Applications
##############

riverctl map normal Super D spawn "rofi -show drun -theme catppuccin-macchiato"
riverctl map normal Super W spawn "rofi -show window -theme catppuccin-macchiato"
riverctl map normal Super E spawn "kitty --class='fm-term' nnn -da -P p"
riverctl map normal Super+Shift E spawn "xdg-open $HOME"

# shellcheck disable=SC2016
riverctl map normal Super+Shift S spawn 'grim -g "$(slurp)" - | wl-copy'

# shellcheck disable=SC2016
riverctl map normal Super+Control+Shift S spawn 'grim -g "$(slurp)" /tmp/grim.png && tesseract -l eng+jpn /tmp/grim.png - | wl-copy && wl-paste | xargs -I{} notify-send "Tesseract" "Copied {}"'

riverctl map normal Super P spawn "grim - | wl-copy"

# shellcheck disable=SC2016
riverctl map normal Super+Shift P spawn 'grim -g "$(slurp -o)" - | wl-copy'


############
# Appearence
############

# Set background and border color
riverctl background-color 0x1e1e2e
riverctl border-color-focused 0xfff4dbd6
riverctl border-color-unfocused 0x001e1e2e
riverctl border-width 2

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 8 &

# cursor
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme Adwaita 24
riverctl focus-follows-cursor always


########
# Inputs
########

# keyboard
riverctl keyboard-layout -options "compose:ralt" us
#
# Set keyboard repeat rate
riverctl set-repeat 50 200

# mouse
riverctl input pointer-13159-6403-EndGameGear_XM1_Gaming_Mouse accel-profile flat

# Clipboard
riverctl map normal Super V spawn 'bash -c "cliphist list | rofi -dmenu | cliphist decode | wl-copy"'


##########
# Monitors
##########

# wlr-randr
# wlr-randr --output HDMI-A-1 --on --mode 1920x1080@60Hz --pos 1920,0 --output DP-1 --on --mode 1920x1080@144.001007Hz --pos 0,0

# kanshi
kanshi &


#######
# Rules
#######

# ssd
riverctl rule-add ssd

# output
riverctl rule-add -app-id 'cs2' output DP-1
riverctl rule-add -app-id 'starrail.exe' output DP-1
riverctl rule-add -app-id 'genshinimpact.exe' output DP-1

# tags
declare -a rule_sets

rule_sets[1]="footclient kitty foot"
rule_sets[2]="LibreWolf firefox"
rule_sets[3]="org.gnome.Nautilus fm-term org.qbittorrent.qBittorrent syncplay"
rule_sets[4]="com.usebottles.bottles cs2 org.prismlauncher.PrismLauncher moe.launcher.an-anime-game-launcher moe.launcher.the-honkers-railway-launcher genshinimpact.exe starrail.exe steam"
rule_sets[5]="org.remmina.Remmina Code VSCodium"
rule_sets[6]="io.github.celluloid_player.Celluloid mpv Spotify"
rule_sets[7]="discord vesktop teams-for-linux 'Microsoft Teams - Preview'"

for index in "${!rule_sets[@]}"; do
    tags=$((1 << (index - 1)))
    read -r -a elements <<< "${rule_sets[index]}"
    for element in "${elements[@]}"; do
        riverctl rule-add -app-id "$element" tags "$tags"
    done
done

# tags+


#########
# Wayland
#########

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


###########
# Autostart
###########

## background
hyprpaper --no-fractional &

## bar
waybar &

## notification daemon
swaync &

## kdeconnect
/usr/lib/kdeconnectd &
kdeconnect-indicator &

## osd
swayosd-server &

# syncthing
flatpak run me.kozec.syncthingtk -m &

# systemctl restarts
systemctl start --user foot-server
systemctl start --user sunshine

## cliphist
wl-paste --type text --watch cliphist store & #Stores only text data
wl-paste --type image --watch cliphist store & #Stores only image data

## lock
swayidle before-sleep 'loginctl lock-session' lock '/home/eric/.config/hypr/bsplock'

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

