#!/bin/bash

hyprpaper >/dev/null 2>&1 &
swayosd-server >/dev/null 2>&1 &
# swayidle before-sleep 'loginctl lock-session' lock 'swaylock' >/dev/null 2>&1 &

wl-clip-persist --clipboard regular &
wl-paste --type text --watch cliphist store >/dev/null 2>&1 &
wl-paste --type image --watch cliphist store >/dev/null 2>&1 &

/usr/lib/polkit-kde-authentication-agent-1 &

systemctl start --user foot-server
systemctl start --user swaync
systemctl restart --user hypridle
systemctl restart --user kanshi
systemctl restart --user waybar
