theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
rulers = [80, 120]
auto-pairs = false

# [editor.smart-tab]
# enable = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "file-encoding", "file-line-ending"]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "position-percentage", "spacer", "mode"]
separator = "│"
mode.normal = ""
mode.insert = ""
mode.select = ""

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it
